name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.13, 3.14 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: |
          uv sync --locked --all-extras --dev

      - name: Run pylint
        run: |
          uv run pylint $(git ls-files '*.py')

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13, 3.14]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: |
          uv sync --locked --all-extras --dev

      - name: Run tests
        run: |
          uv run pytest tests